name: Build Jekyll Site

on:
  push:
    branches:
      - main  # Adjust this to your repository's default branch

jobs:
  build:
    runs-on: ubuntu-latest  # The operating system for the build
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # This action checks out your repository
      
      - name: Set up Ruby
        uses: actions/setup-ruby@v2
        with:
          ruby-version: 3.1.3p185 # Specify the version of Ruby you're using
        
      - name: Install Dependencies
        run: |
          gem install bundler  # Install Bundler
          bundle install      # Install Jekyll and other gems
        
      - name: Build Jekyll Site
        run: bundle exec jekyll build  # Command to build your Jekyll site
