name: Access Secrets Example

on:
  push:
    branches:
      - main

jobs:
  access_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Access Secret
        run: |
          echo "API Key: $API_KEY"
